apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-billing-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-billing-aggregator
  template:
    metadata:
      labels:
        app: cloud-billing-aggregator
    spec:
      containers:
      - name: app
        image: cloud-billing-aggregator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
