apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-frontend
  labels:
    app: billing-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-frontend
  template:
    metadata:
      labels:
        app: billing-frontend
    spec:
      containers:
        - name: frontend
          image: billing-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
